#!/usr/bin/env python3
"""
Comprehensive Breaking Changes Analysis Script

This single script analyzes all CSV files generated by the Java breaking changes analysis
and creates comprehensive summary statistics, visualizations, and reports.

Usage: python comprehensive_analysis.py
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import glob
import os
from collections import Counter, defaultdict
import warnings
from datetime import datetime
warnings.filterwarnings('ignore')

# Set up plotting style
plt.style.use('default')
sns.set_palette("husl")

class ComprehensiveBreakingChangesAnalyzer:
    def __init__(self, base_path=None):
        if base_path is None:
            base_path = Path.cwd()
        self.base_path = Path(base_path)
        self.csv_path = self.base_path / "data" / "rq3" / "csv"
        self.output_path = self.base_path / "analysis_results"
        self.output_path.mkdir(exist_ok=True)
        
        # Data containers
        self.all_breaking_changes = []
        self.used_breaking_changes = []
        self.projects_analyzed = set()
        
    def load_data(self):
        """Load all CSV files from the analysis results"""
        print("🔄 Loading data from CSV files...")
        
        # Find all CSV files
        all_bc_files = glob.glob(str(self.csv_path / "**" / "*-all-breaking-changes.csv"), recursive=True)
        used_bc_files = glob.glob(str(self.csv_path / "**" / "*-used-breaking-changes.csv"), recursive=True)
        
        print(f"   Found {len(all_bc_files)} all-breaking-changes files")
        print(f"   Found {len(used_bc_files)} used-breaking-changes files")
        
        # Load all breaking changes
        for file_path in all_bc_files:
            try:
                df = pd.read_csv(file_path)
                if not df.empty:
                    project_name = Path(file_path).parent.name
                    self.projects_analyzed.add(project_name)
                    df['Project'] = project_name
                    self.all_breaking_changes.append(df)
            except Exception as e:
                print(f"   Warning: Could not load {file_path}: {e}")
                
        # Load used breaking changes
        for file_path in used_bc_files:
            try:
                df = pd.read_csv(file_path)
                if not df.empty:
                    project_name = Path(file_path).parent.name
                    df['Project'] = project_name
                    self.used_breaking_changes.append(df)
            except Exception as e:
                print(f"   Warning: Could not load {file_path}: {e}")
        
        # Combine all data
        if self.all_breaking_changes:
            self.all_bc_df = pd.concat(self.all_breaking_changes, ignore_index=True)
        else:
            self.all_bc_df = pd.DataFrame()
            
        if self.used_breaking_changes:
            self.used_bc_df = pd.concat(self.used_breaking_changes, ignore_index=True)
        else:
            self.used_bc_df = pd.DataFrame()
            
        print(f"   ✅ Loaded data for {len(self.projects_analyzed)} projects")
        print(f"   📊 Total breaking changes: {len(self.all_bc_df):,}")
        print(f"   🎯 Total used breaking changes: {len(self.used_bc_df):,}")
        
    def generate_summary_stats(self):
        """Generate comprehensive summary statistics"""
        print("📈 Generating summary statistics...")
        
        summary = {
            'total_projects_analyzed': len(self.projects_analyzed),
            'total_breaking_changes': len(self.all_bc_df),
            'total_used_breaking_changes': len(self.used_bc_df),
            'usage_rate': (len(self.used_bc_df) / len(self.all_bc_df) * 100) if len(self.all_bc_df) > 0 else 0
        }
        
        if not self.all_bc_df.empty:
            # Library analysis
            library_counts = self.all_bc_df['Library_Name'].value_counts()
            summary['most_problematic_libraries'] = library_counts.head(15).to_dict()
            summary['total_unique_libraries'] = len(library_counts)
            
            # Change type analysis
            change_type_counts = self.all_bc_df['Change_Type'].value_counts()
            summary['most_common_change_types'] = change_type_counts.head(10).to_dict()
            
            # Compatibility analysis
            binary_compat_rate = (self.all_bc_df['Binary_Compatible'].sum() / len(self.all_bc_df) * 100)
            source_compat_rate = (self.all_bc_df['Source_Compatible'].sum() / len(self.all_bc_df) * 100)
            summary['binary_compatibility_rate'] = binary_compat_rate
            summary['source_compatibility_rate'] = source_compat_rate
            
            # Direct vs Transitive
            direct_changes = len(self.all_bc_df[self.all_bc_df['Is_Transitive'] == False])
            transitive_changes = len(self.all_bc_df[self.all_bc_df['Is_Transitive'] == True])
            summary['direct_breaking_changes'] = direct_changes
            summary['transitive_breaking_changes'] = transitive_changes

            # Used direct vs transitive
            if not self.used_bc_df.empty:
                direct_used = len(self.used_bc_df[self.used_bc_df['Is_Transitive'] == False])
                transitive_used = len(self.used_bc_df[self.used_bc_df['Is_Transitive'] == True])
                summary['direct_used_breaking_changes'] = direct_used
                summary['transitive_used_breaking_changes'] = transitive_used
            else:
                summary['direct_used_breaking_changes'] = 0
                summary['transitive_used_breaking_changes'] = 0

            
            # Release type analysis
            if 'Release_Type' in self.all_bc_df.columns:
                release_type_counts = self.all_bc_df['Release_Type'].value_counts()
                summary['changes_by_release_type'] = release_type_counts.to_dict()
            
            # Project-level statistics
            project_stats = self.all_bc_df.groupby('Project').agg({
                'Library_Name': 'count',
                'Is_Used_In_Client': 'sum'
            }).rename(columns={'Library_Name': 'total_changes', 'Is_Used_In_Client': 'used_changes'})
            
            summary['avg_breaking_changes_per_project'] = project_stats['total_changes'].mean()
            summary['avg_used_changes_per_project'] = project_stats['used_changes'].mean()
            summary['projects_with_used_changes'] = len(project_stats[project_stats['used_changes'] > 0])
        
        return summary
    
    def save_all_csv_files(self, summary):
        """Save all summary data to CSV files"""
        print("💾 Saving data to CSV files...")
        
        # Main summary stats
        summary_data = []
        for key, value in summary.items():
            if not isinstance(value, dict):
                summary_data.append({'Metric': key, 'Value': value})
        
        summary_df = pd.DataFrame(summary_data)
        summary_df.to_csv(self.output_path / 'summary_statistics.csv', index=False)

        # Append used direct/transitive rows
        extra_rows = [
            {'Metric': 'direct_used_breaking_changes', 'Value': summary.get('direct_used_breaking_changes', 0)},
            {'Metric': 'transitive_used_breaking_changes', 'Value': summary.get('transitive_used_breaking_changes', 0)}
        ]
        extra_df = pd.DataFrame(extra_rows)
        summary_df = pd.concat([summary_df, extra_df], ignore_index=True)
        summary_df.to_csv(self.output_path / 'summary_statistics.csv', index=False)

        
        # Most problematic libraries
        if 'most_problematic_libraries' in summary:
            lib_df = pd.DataFrame(list(summary['most_problematic_libraries'].items()), 
                                columns=['Library', 'Breaking_Changes_Count'])
            lib_df.to_csv(self.output_path / 'most_problematic_libraries.csv', index=False)
        
        # Change types
        if 'most_common_change_types' in summary:
            change_df = pd.DataFrame(list(summary['most_common_change_types'].items()), 
                                   columns=['Change_Type', 'Count'])
            change_df.to_csv(self.output_path / 'change_types_summary.csv', index=False)
        
        # Project-level details
        if not self.all_bc_df.empty:
            project_details = self.all_bc_df.groupby('Project').agg({
                'Library_Name': 'count',
                'Is_Used_In_Client': 'sum',
                'Binary_Compatible': 'mean',
                'Source_Compatible': 'mean',
                'Is_Transitive': lambda x: (x == True).sum(),
            }).rename(columns={
                'Library_Name': 'Total_Breaking_Changes',
                'Is_Used_In_Client': 'Used_Breaking_Changes',
                'Binary_Compatible': 'Binary_Compatibility_Rate',
                'Source_Compatible': 'Source_Compatibility_Rate',
                'Is_Transitive': 'Transitive_Changes'
            })
            
            project_details['Usage_Rate'] = (project_details['Used_Breaking_Changes'] / 
                                           project_details['Total_Breaking_Changes'] * 100)
            project_details.to_csv(self.output_path / 'project_level_summary.csv')
    
    def create_all_visualizations(self, summary):
        """Create all key visualizations"""
        print("🎨 Creating visualizations...")
        
        plt.rcParams['figure.figsize'] = (12, 8)
        plt.rcParams['font.size'] = 10
        
        # 1. Overview Dashboard
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(16, 12))
        fig.suptitle('Breaking Changes Analysis Overview', fontsize=16, fontweight='bold')
        
        # Total counts
        categories = ['Total\nProjects', 'Total\nBreaking Changes', 'Used\nBreaking Changes', 'Unique\nLibraries']
        values = [
            summary['total_projects_analyzed'],
            summary['total_breaking_changes'],
            summary['total_used_breaking_changes'],
            summary.get('total_unique_libraries', 0)
        ]
        
        bars1 = ax1.bar(categories, values, color=['#3498db', '#e74c3c', '#f39c12', '#2ecc71'])
        ax1.set_title('Analysis Overview', fontweight='bold')
        ax1.set_ylabel('Count')
        
        for bar, value in zip(bars1, values):
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height + height*0.01,
                    f'{int(value):,}', ha='center', va='bottom', fontweight='bold')
        
        # Usage rate pie chart
        if summary['total_breaking_changes'] > 0:
            used = summary['total_used_breaking_changes']
            unused = summary['total_breaking_changes'] - used
            ax2.pie([used, unused], labels=['Used', 'Unused'], autopct='%1.1f%%',
                   colors=['#e74c3c', '#95a5a6'], startangle=90)
            ax2.set_title(f'Breaking Changes Usage\n({summary["usage_rate"]:.1f}% used)', fontweight='bold')
        
        # Compatibility rates
        if 'binary_compatibility_rate' in summary:
            compat_data = [summary['binary_compatibility_rate'], summary['source_compatibility_rate']]
            ax3.bar(['Binary\nCompatible', 'Source\nCompatible'], compat_data, color=['#9b59b6', '#1abc9c'])
            ax3.set_title('Compatibility Rates', fontweight='bold')
            ax3.set_ylabel('Percentage (%)')
            ax3.set_ylim(0, 100)
            
            for i, v in enumerate(compat_data):
                ax3.text(i, v + 1, f'{v:.1f}%', ha='center', va='bottom', fontweight='bold')
        
        # Direct vs Transitive
        if 'direct_breaking_changes' in summary:
            direct = summary['direct_breaking_changes']
            transitive = summary['transitive_breaking_changes']
            ax4.pie([direct, transitive], labels=['Direct', 'Transitive'], autopct='%1.1f%%',
                   colors=['#34495e', '#f1c40f'], startangle=90)
            ax4.set_title('Direct vs Transitive Changes', fontweight='bold')
        
        plt.tight_layout()
        plt.savefig(self.output_path / 'overview_dashboard.png', dpi=300, bbox_inches='tight')
        plt.close()
        
        # 2. Top Problematic Libraries
        if 'most_problematic_libraries' in summary and summary['most_problematic_libraries']:
            fig, ax = plt.subplots(figsize=(14, 8))
            
            libs = list(summary['most_problematic_libraries'].keys())[:15]
            counts = list(summary['most_problematic_libraries'].values())[:15]
            short_libs = [lib.split(':')[-1] if ':' in lib else lib for lib in libs]
            
            bars = ax.barh(range(len(short_libs)), counts, color=plt.cm.viridis(np.linspace(0, 1, len(short_libs))))
            ax.set_yticks(range(len(short_libs)))
            ax.set_yticklabels(short_libs)
            ax.set_xlabel('Number of Breaking Changes')
            ax.set_title('Top 15 Most Problematic Libraries', fontsize=14, fontweight='bold')
            
            for i, (bar, count) in enumerate(zip(bars, counts)):
                ax.text(count + max(counts)*0.01, i, str(int(count)), 
                       va='center', ha='left', fontweight='bold')
            
            plt.tight_layout()
            plt.savefig(self.output_path / 'top_problematic_libraries.png', dpi=300, bbox_inches='tight')
            plt.close()
        
        # 3. Change Types Distribution
        if 'most_common_change_types' in summary and summary['most_common_change_types']:
            fig, ax = plt.subplots(figsize=(14, 10))
            
            change_types = list(summary['most_common_change_types'].keys())[:10]
            counts = list(summary['most_common_change_types'].values())[:10]
            
            # Better label processing - keep more meaningful parts
            short_types = []
            for ct in change_types:
                if 'METHOD_' in ct:
                    short_types.append(ct.replace('METHOD_', 'Method\n'))
                elif 'CLASS_' in ct:
                    short_types.append(ct.replace('CLASS_', 'Class\n'))
                elif 'FIELD_' in ct:
                    short_types.append(ct.replace('FIELD_', 'Field\n'))
                elif 'CONSTRUCTOR_' in ct:
                    short_types.append(ct.replace('CONSTRUCTOR_', 'Constructor\n'))
                else:
                    # For other types, just use first word and add line break
                    parts = ct.split('_')
                    if len(parts) > 1:
                        short_types.append(f"{parts[0]}\n{parts[1]}" if len(parts[1]) > 0 else parts[0])
                    else:
                        short_types.append(ct)
            
            bars = ax.bar(range(len(short_types)), counts, 
                         color=plt.cm.Set3(np.linspace(0, 1, len(short_types))))
            ax.set_xticks(range(len(short_types)))
            ax.set_xticklabels(short_types, rotation=0, ha='center', fontsize=10)
            ax.set_ylabel('Number of Changes', fontsize=12)
            ax.set_title('Top 10 Most Common Change Types', fontsize=14, fontweight='bold', pad=20)
            
            # Add value labels on top of bars
            for bar, count in zip(bars, counts):
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height + height*0.01,
                       f'{int(count):,}', ha='center', va='bottom', fontweight='bold', fontsize=9)
            
            # Adjust layout to prevent label cutoff
            plt.subplots_adjust(bottom=0.15, top=0.9)
            plt.savefig(self.output_path / 'change_types_distribution.png', dpi=300, bbox_inches='tight')
            plt.close()
        
        # 4. Project-level Analysis
        if not self.all_bc_df.empty:
            project_stats = self.all_bc_df.groupby('Project').agg({
                'Library_Name': 'count',
                'Is_Used_In_Client': 'sum'
            }).rename(columns={'Library_Name': 'total_changes', 'Is_Used_In_Client': 'used_changes'})
            
            fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
            
            ax1.hist(project_stats['total_changes'], bins=30, color='#3498db', alpha=0.7, edgecolor='black')
            ax1.set_xlabel('Number of Breaking Changes')
            ax1.set_ylabel('Number of Projects')
            ax1.set_title('Distribution of Breaking Changes per Project', fontweight='bold')
            ax1.axvline(project_stats['total_changes'].mean(), color='red', linestyle='--', 
                       label=f'Mean: {project_stats["total_changes"].mean():.1f}')
            ax1.legend()
            
            usage_rates = (project_stats['used_changes'] / project_stats['total_changes'] * 100).fillna(0)
            ax2.hist(usage_rates, bins=20, color='#e74c3c', alpha=0.7, edgecolor='black')
            ax2.set_xlabel('Usage Rate (%)')
            ax2.set_ylabel('Number of Projects')
            ax2.set_title('Distribution of Breaking Change Usage Rates', fontweight='bold')
            ax2.axvline(usage_rates.mean(), color='blue', linestyle='--', 
                       label=f'Mean: {usage_rates.mean():.1f}%')
            ax2.legend()
            
            plt.tight_layout()
            plt.savefig(self.output_path / 'project_level_analysis.png', dpi=300, bbox_inches='tight')
            plt.close()
    
    def generate_markdown_report(self, summary):
        """Generate comprehensive markdown report"""
        print("📝 Generating comprehensive report...")
        
        # Load additional data for report
        try:
            libraries_df = pd.read_csv(self.output_path / "most_problematic_libraries.csv")
            change_types_df = pd.read_csv(self.output_path / "change_types_summary.csv")
            project_df = pd.read_csv(self.output_path / "project_level_summary.csv")
        except:
            return
        
        markdown_content = f"""# Breaking Changes Analysis Report

**Generated on:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Executive Summary

This report analyzes breaking changes across **{int(summary['total_projects_analyzed']):,}** Java projects, examining dependency updates and their impact on client code. The analysis identified **{int(summary['total_breaking_changes']):,}** total breaking changes, of which only **{int(summary['total_used_breaking_changes']):,}** ({summary['usage_rate']:.2f}%) were actually used in client code.

### Key Findings

- 📊 **{int(summary['total_projects_analyzed']):,}** projects analyzed
- 🚨 **{int(summary['total_breaking_changes']):,}** total breaking changes detected  
- ✅ **{int(summary['total_used_breaking_changes']):,}** breaking changes actually used in client code
- 📈 **{summary['usage_rate']:.2f}%** overall usage rate
- 📚 **{int(summary['total_unique_libraries']):,}** unique libraries with breaking changes
- 🎯 **{int(summary['projects_with_used_changes']):,}** projects ({summary['projects_with_used_changes']/summary['total_projects_analyzed']*100:.1f}%) have used breaking changes

## Detailed Analysis

### 1. Breaking Changes Overview

| Metric | Value |
|--------|-------|
| **Total Projects Analyzed** | {int(summary['total_projects_analyzed']):,} |
| **Total Breaking Changes** | {int(summary['total_breaking_changes']):,} |
| **Used Breaking Changes** | {int(summary['total_used_breaking_changes']):,} |
| **Usage Rate** | {summary['usage_rate']:.2f}% |
| **Unique Libraries with Changes** | {int(summary['total_unique_libraries']):,} |

### 2. Change Distribution

| Type | Count | Percentage |
|------|-------|------------|
| **Direct Changes** | {int(summary['direct_breaking_changes']):,} | {summary['direct_breaking_changes']/(summary['direct_breaking_changes']+summary['transitive_breaking_changes'])*100:.1f}% |
| **Transitive Changes** | {int(summary['transitive_breaking_changes']):,} | {summary['transitive_breaking_changes']/(summary['direct_breaking_changes']+summary['transitive_breaking_changes'])*100:.1f}% |

### 2.1 Used Breaking Changes Distribution

| Type | Count | Percentage |
|------|-------|------------|
| **Direct (Used)** | {int(summary['direct_used_breaking_changes']):,} | {summary['direct_used_breaking_changes']/(summary['direct_used_breaking_changes']+summary['transitive_used_breaking_changes'])*100 if (summary['direct_used_breaking_changes']+summary['transitive_used_breaking_changes'])>0 else 0:.1f}% |
| **Transitive (Used)** | {int(summary['transitive_used_breaking_changes']):,} | {summary['transitive_used_breaking_changes']/(summary['direct_used_breaking_changes']+summary['transitive_used_breaking_changes'])*100 if (summary['direct_used_breaking_changes']+summary['transitive_used_breaking_changes'])>0 else 0:.1f}% |


### 3. Top Problematic Libraries

| Rank | Library | Breaking Changes |
|------|---------|------------------|"""

        for i, (_, row) in enumerate(libraries_df.head(10).iterrows(), 1):
            markdown_content += f"\n| {i} | `{row['Library']}` | {int(row['Breaking_Changes_Count']):,} |"

        markdown_content += f"""

### 4. Most Common Change Types

| Rank | Change Type | Count | Percentage |
|------|-------------|-------|------------|"""

        total_changes = change_types_df['Count'].sum()
        for i, (_, row) in enumerate(change_types_df.head(5).iterrows(), 1):
            percentage = (row['Count'] / total_changes) * 100
            markdown_content += f"\n| {i} | `{row['Change_Type']}` | {int(row['Count']):,} | {percentage:.1f}% |"

        markdown_content += f"""

## Key Insights

### 🎯 Low Overall Usage Rate
Despite {int(summary['total_breaking_changes']):,} breaking changes detected, only **{summary['usage_rate']:.2f}%** are actually used in client code.

### 📚 Library Concentration  
- **Jackson Databind** contributes {libraries_df.iloc[0]['Breaking_Changes_Count']/summary['total_breaking_changes']*100:.1f}% of all changes
- Top 5 libraries account for a significant portion of breaking changes

### 🔧 Method Changes Dominate
**{change_types_df.iloc[0]['Count']/total_changes*100:.1f}%** of all breaking changes are method-related.

### 🌐 Transitive Impact
**{summary['transitive_breaking_changes']/(summary['direct_breaking_changes']+summary['transitive_breaking_changes'])*100:.1f}%** of breaking changes come from transitive dependencies.

### ⚠️ Poor Compatibility
- Only **{summary['binary_compatibility_rate']:.1f}%** maintain binary compatibility
- **{summary['source_compatibility_rate']:.1f}%** maintain source compatibility

---
*Generated by comprehensive_analysis.py*
"""

        # Save the report
        with open(self.output_path / "ANALYSIS_REPORT.md", 'w', encoding='utf-8') as f:
            f.write(markdown_content)
    
    def print_final_summary(self, summary):
        """Print final comprehensive summary"""
        try:
            libraries_df = pd.read_csv(self.output_path / "most_problematic_libraries.csv")
            change_types_df = pd.read_csv(self.output_path / "change_types_summary.csv")
        except:
            libraries_df = pd.DataFrame()
            change_types_df = pd.DataFrame()
        
        print("\n" + "="*80)
        print("🚨 BREAKING CHANGES ANALYSIS - FINAL SUMMARY")
        print("="*80)
        
        print(f"\n📊 SCALE:")
        print(f"   • {int(summary['total_projects_analyzed']):,} Java projects analyzed")
        print(f"   • {int(summary['total_breaking_changes']):,} breaking changes detected")
        print(f"   • {int(summary['total_unique_libraries']):,} unique libraries involved")
        
        print(f"\n🎯 KEY FINDING: Only {summary['usage_rate']:.2f}% of breaking changes are actually used!")
        print(f"   • {int(summary['total_used_breaking_changes']):,} out of {int(summary['total_breaking_changes']):,} changes affect client code")
        print(f"   • {int(summary['projects_with_used_changes']):,} projects ({summary['projects_with_used_changes']/summary['total_projects_analyzed']*100:.1f}%) have any used breaking changes")
        
        if not libraries_df.empty:
            print(f"\n🏆 TOP 3 MOST PROBLEMATIC LIBRARIES:")
            for i in range(min(3, len(libraries_df))):
                print(f"   {i+1}. {libraries_df.iloc[i]['Library']}: {int(libraries_df.iloc[i]['Breaking_Changes_Count']):,} changes")
        
        print(f"\n⚡ CHANGE BREAKDOWN:")
        print(f"   • Direct: {int(summary['direct_breaking_changes']):,} ({summary['direct_breaking_changes']/(summary['direct_breaking_changes']+summary['transitive_breaking_changes'])*100:.0f}%)")
        print(f"   • Transitive: {int(summary['transitive_breaking_changes']):,} ({summary['transitive_breaking_changes']/(summary['direct_breaking_changes']+summary['transitive_breaking_changes'])*100:.0f}%)")
        
        print(f"\n💥 COMPATIBILITY IMPACT:")
        print(f"   • Binary Compatible: {summary['binary_compatibility_rate']:.1f}%")
        print(f"   • Source Compatible: {summary['source_compatibility_rate']:.1f}%")
        
        if not change_types_df.empty:
            print(f"\n🔧 CHANGE TYPES:")
            total = change_types_df['Count'].sum()
            for i in range(min(3, len(change_types_df))):
                pct = change_types_df.iloc[i]['Count']/total*100
                print(f"   • {change_types_df.iloc[i]['Change_Type']}: {int(change_types_df.iloc[i]['Count']):,} ({pct:.0f}%)")
        
        print(f"\n💡 BOTTOM LINE:")
        print(f"   Breaking changes are common but most don't affect real usage.")
        print(f"   Focus on the {summary['usage_rate']:.2f}% that actually matter!")
        
        print(f"\n📁 All results saved to: {self.output_path}")
        print("   • CSV files with detailed data")
        print("   • PNG visualizations")  
        print("   • Comprehensive markdown report")
        print("="*80)
    
    def run_complete_analysis(self):
        """Run the complete analysis pipeline"""
        print("🚀 Starting Comprehensive Breaking Changes Analysis...")
        print("="*60)
        
        # Load data
        self.load_data()
        
        if self.all_bc_df.empty:
            print("❌ No data found! Please check your CSV files.")
            return
        
        # Generate summary statistics
        summary = self.generate_summary_stats()
        
        # Save all CSV files
        self.save_all_csv_files(summary)
        
        # Create all visualizations
        self.create_all_visualizations(summary)
        
        # Generate comprehensive report
        self.generate_markdown_report(summary)
        
        # Print final summary
        self.print_final_summary(summary)
        
        print(f"\n✅ Complete analysis finished! Check '{self.output_path}' for all results.")


def main():
    """Main function to run the analysis"""
    # Auto-detect the project directory or use current directory
    current_dir = Path.cwd()
    if (current_dir / "data" / "rq3" / "csv").exists():
        base_path = current_dir
    else:
        # Try to find the project directory
        possible_paths = [
            Path("/Users/tonyyin/Desktop/Courses/SOFTENG700/part4-project"),
            current_dir.parent,
            current_dir
        ]
        
        base_path = None
        for path in possible_paths:
            if (path / "data" / "rq3" / "csv").exists():
                base_path = path
                break
        
        if base_path is None:
            print("❌ Could not find data directory. Please run from the project root.")
            return
    
    analyzer = ComprehensiveBreakingChangesAnalyzer(base_path)
    analyzer.run_complete_analysis()


if __name__ == "__main__":
    main()