<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>research-project</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>research-project</name>
  <url>http://maven.apache.org</url>
  <parent>
    <groupId>com.example</groupId>
    <artifactId>research-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>com.example.depanalyzer</groupId>
      <artifactId>depanalyzer</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <mainClass>com.example.Script</mainClass>
          <options>
            <option>-Xmx16g</option>
            <option>-Xms4g</option>
            <option>-XX:+UseG1GC</option>
            <option>-XX:MaxGCPauseMillis=200</option>
            <option>-XX:+DisableExplicitGC</option>
            <option>-XX:+UseStringDeduplication</option>
            <option>-XX:MaxMetaspaceSize=2g</option>
            <option>-XX:+UnlockExperimentalVMOptions</option>
            <option>-XX:+UseZGC</option>
            <option>-XX:+UseLargePages</option>
          </options>
        </configuration>
      </plugin>
    </plugins>
  </build>


</project>